### ISSUE TITLE
Add psite estimation with plastid

### ISSUE THREAD

**Issue by pinin4fjords** [nf-core/riboseq#21]
### Description of feature

See https://plastid.readthedocs.io/en/latest/generated/plastid.bin.psite.html#module-plastid.bin.psite

Add a plastid/psite module to nf-core/modules, and then here.

**Comment by JackCurragh** [comment]
This is likely a valid tool to use but relating to my recent comment on #24 these older offset predictors don't quite work for certain kinds of samples. 

There are a newer kind of P-Site predictors coming about that do it on a read-by-read basis rather than read length-by-read length. [For example, psite](https://github.com/gxelab/psite). The [paper](https://www.biorxiv.org/content/10.1101/2023.06.27.546788v1.full.pdf) has just one figure so you may be able to see how it works for MNase data.

**Comment by pinin4fjords** [comment]
Thanks! Plastid was specifically requested in our agreement with Altos, but could you make a separate issue for Psite? A quick look suggests it's not in Bioconda yet, so that will be the first job.

**Comment by JackCurragh** [comment]
Is this still needed for v1.10? What does it add that the tools that we have atm don't provide? It is my understanding that each 'Ribo-Seq specific' tool that we have already does this step in their own way. Is Plastid desired for some other reason?

**Comment by pinin4fjords** [comment]
Yep, you may be right. I'll remove it from the milestone.
